# Generated by Django 5.2.4 on 2025-07-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SISTEMA", "Sistema"),
                    ("AFILIACION", "Afiliación"),
                    ("SERVICIOS", "Servicios"),
                    ("CONTENIDO", "Contenido"),
                ],
                db_index=True,
                default="SISTEMA",
                max_length=20,
                verbose_name="Tipo de Notificación",
            ),
        ),
    ]
