# Generated by Django 5.2.4 on 2025-07-29 01:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto del Servicio",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Verificación"),
                            ("VERIFICADO", "Verificado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado del Pago",
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        help_text="Archivo del comprobante subido por el usuario.",
                        upload_to="pagos/comprobantes/%Y/%m/",
                        verbose_name="Comprobante de Pago",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "fecha_verificacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Verificación"
                    ),
                ),
                (
                    "gestor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_verificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verificado por",
                    ),
                ),
                (
                    "solicitud_servicio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="services.solicitudservicio",
                        verbose_name="Solicitud de Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
