# Generated by Django 5.2.4 on 2025-07-20 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("memberships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="perfil",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de perfil del usuario.",
                        null=True,
                        upload_to="perfiles/avatares/",
                        verbose_name="Avatar",
                    ),
                ),
                ("biografia", models.TextField(blank=True, verbose_name="Biografía")),
                (
                    "redes_sociales",
                    models.JSONField(
                        blank=True,
                        help_text="Ej: {'twitter': 'https://twitter.com/usuario', 'linkedin': '...'}",
                        null=True,
                        verbose_name="Redes Sociales",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
        migrations.CreateModel(
            name="Membresia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_socio",
                    models.CharField(
                        help_text="Identificador único y permanente para el socio.",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Socio",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("SUSPENDIDA", "Suspendida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_index=True,
                        default="ACTIVA",
                        max_length=20,
                        verbose_name="Estado de la Membresía",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        help_text="Fecha oficial de inicio de la membresía.",
                        verbose_name="Fecha de Ingreso",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membresias_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "solicitud_origen",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membresia_generada",
                        to="memberships.solicitudafiliacion",
                        verbose_name="Solicitud de Origen",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Socio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresía",
                "verbose_name_plural": "Membresías",
                "ordering": ["-fecha_ingreso", "usuario__username"],
            },
        ),
    ]
