# Generated by Django 5.2.4 on 2025-07-22 02:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Categoría de Servicio",
                "verbose_name_plural": "Categorías de Servicios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Convenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_entidad",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Entidad"
                    ),
                ),
                (
                    "contacto",
                    models.TextField(
                        blank=True, verbose_name="Información de Contacto"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Convenio",
                "verbose_name_plural": "Convenios",
            },
        ),
        migrations.CreateModel(
            name="Beneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Beneficio"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficios",
                        to="services.categoriaservicio",
                    ),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios",
                        to="services.convenio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficio",
                "verbose_name_plural": "Beneficios",
            },
        ),
        migrations.CreateModel(
            name="DetalleBeneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion_descuento",
                    models.CharField(
                        max_length=255, verbose_name="Descripción del Descuento"
                    ),
                ),
                (
                    "beneficio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="services.beneficio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecursoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Salón A, Dr. Pérez",
                        max_length=200,
                        verbose_name="Nombre del Recurso",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PERSONA", "Persona"), ("FISICO", "Recurso Físico")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recursos_a_cargo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso de Servicio",
                "verbose_name_plural": "Recursos de Servicio",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HorarioDisponible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora_inicio",
                    models.DateTimeField(verbose_name="Inicio de la Disponibilidad"),
                ),
                (
                    "fecha_hora_fin",
                    models.DateTimeField(verbose_name="Fin de la Disponibilidad"),
                ),
                (
                    "esta_reservado",
                    models.BooleanField(default=False, verbose_name="¿Está reservado?"),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="services.recursoservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario Disponible",
                "verbose_name_plural": "Horarios Disponibles",
                "ordering": ["fecha_hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Servicio"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción detallada")),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarca para ocultar este servicio del catálogo.",
                        verbose_name="¿Está activo?",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicios",
                        to="services.categoriaservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="recursoservicio",
            name="servicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recursos",
                to="services.servicio",
            ),
        ),
        migrations.CreateModel(
            name="DetalleCobertura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_cobertura",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Cobertura"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor o Monto"
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coberturas",
                        to="services.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Cobertura",
                "verbose_name_plural": "Detalles de Cobertura",
            },
        ),
        migrations.CreateModel(
            name="SolicitudServicio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_hora_inicio",
                    models.DateTimeField(
                        verbose_name="Inicio de la Reserva Solicitada"
                    ),
                ),
                (
                    "fecha_hora_fin",
                    models.DateTimeField(verbose_name="Fin de la Reserva Solicitada"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Aprobación"),
                            ("CONFIRMADA", "Confirmada"),
                            ("RECHAZADA", "Rechazada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas_usuario",
                    models.TextField(blank=True, verbose_name="Notas del Usuario"),
                ),
                (
                    "respuesta_gestor",
                    models.TextField(blank=True, verbose_name="Respuesta del Gestor"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "gestor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_gestionadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="services.recursoservicio",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_servicio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Servicio",
                "verbose_name_plural": "Solicitudes de Servicio",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
