# Generated by Django 5.2.4 on 2025-07-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudservicio",
            name="fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fin de la Reserva Solicitada"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudservicio",
            name="fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Inicio de la Reserva Solicitada"
            ),
        ),
    ]
