# Generated by Django 5.2.4 on 2025-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallesolicitudnatural",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="detallesolicitudnatural",
            name="nombres",
        ),
        migrations.AlterField(
            model_name="detallesolicitudnatural",
            name="cedula",
            field=models.CharField(max_length=10, verbose_name="Cédula"),
        ),
    ]
