# Generated by Django 5.2.4 on 2025-07-22 02:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudAfiliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_REVISION", "En Revisión"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_afiliacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Afiliación",
                "verbose_name_plural": "Solicitudes de Afiliación",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DetalleSolicitudJuridica",
            fields=[
                (
                    "solicitud",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="memberships.solicitudafiliacion",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=255, verbose_name="Razón Social"),
                ),
                (
                    "ruc",
                    models.CharField(max_length=13, unique=True, verbose_name="RUC"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Comercial"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        max_length=255, verbose_name="Dirección Principal"
                    ),
                ),
                (
                    "celular_empresa",
                    models.CharField(
                        max_length=20, verbose_name="Celular de la Empresa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Solicitud (P. Jurídica)",
                "verbose_name_plural": "Detalles de Solicitud (P. Jurídica)",
            },
        ),
        migrations.CreateModel(
            name="DetalleSolicitudNatural",
            fields=[
                (
                    "solicitud",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="memberships.solicitudafiliacion",
                    ),
                ),
                ("nombres", models.CharField(max_length=150, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=150, verbose_name="Apellidos"),
                ),
                (
                    "cedula",
                    models.CharField(max_length=10, unique=True, verbose_name="Cédula"),
                ),
                (
                    "direccion",
                    models.CharField(
                        max_length=255, verbose_name="Dirección Principal"
                    ),
                ),
                ("celular", models.CharField(max_length=20, verbose_name="Celular")),
            ],
            options={
                "verbose_name": "Detalle de Solicitud (P. Natural)",
                "verbose_name_plural": "Detalles de Solicitud (P. Natural)",
            },
        ),
        migrations.CreateModel(
            name="DocumentoAdjunto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre_documento",
                    models.CharField(
                        help_text="Ej: Copia de Cédula, RUC, Nombramiento de Representante Legal",
                        max_length=200,
                        verbose_name="Nombre del Documento",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="solicitud_documentos/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="memberships.solicitudafiliacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Adjunto",
                "verbose_name_plural": "Documentos Adjuntos",
            },
        ),
        migrations.CreateModel(
            name="BeneficiarioPoliza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        max_length=255, verbose_name="Nombre Completo del Beneficiario"
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ej: 50.00 para 50%",
                        max_digits=5,
                        verbose_name="Porcentaje",
                    ),
                ),
                (
                    "solicitud_natural",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiarios",
                        to="memberships.detallesolicitudnatural",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiario de Póliza",
                "verbose_name_plural": "Beneficiarios de Póliza",
            },
        ),
    ]
