# Generated by Django 5.2.4 on 2025-07-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_evento",
                    models.CharField(
                        help_text="Identificador único para el evento, ej: SOLICITUD_APROBADA",
                        max_length=100,
                        unique=True,
                        verbose_name="Código del Evento",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "mensaje_plantilla",
                    models.CharField(
                        help_text="Usa placeholders como {solicitante} o {estado}.",
                        max_length=255,
                        verbose_name="Plantilla del Mensaje",
                    ),
                ),
                (
                    "esta_activa",
                    models.BooleanField(default=True, verbose_name="¿Está activa?"),
                ),
            ],
            options={
                "verbose_name": "Configuración de Notificación",
                "verbose_name_plural": "Configuraciones de Notificaciones",
            },
        ),
    ]
