"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-@&h9y%z1rb=u880@(5(ntx(!$n4=my+-9#g@#qy)2f0bm#5y+h"

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'core.apps.CoreConfig',  # App para la landing page y vistas generales.
    'users.apps.UsersConfig',  # App para usuarios, perfiles y membresías.
    'memberships.apps.MembershipsConfig',  # App para el flujo de solicitudes de afiliación.
    'services.apps.ServicesConfig',  # App para el catálogo de servicios y reservas.
    'content.apps.ContentConfig',  # App para el sistema de noticias y contenido.
    "communications.apps.CommunicationsConfig",  # App para las notificaciones de usuario.
    'staff_panel.apps.StaffPanelConfig',  # App para el panel de gestión del personal.
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Directorio para plantillas globales
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# --- Gestión de Archivos Estáticos y de Medios ---
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# URL para referirse a los archivos subidos por los usuarios
MEDIA_URL = '/media/'
# Carpeta donde se guardarán físicamente los archivos subidos por los usuarios.
MEDIA_ROOT = BASE_DIR / 'media'

# --- Configuración de Autenticación y Redirecciones ---
LOGIN_REDIRECT_URL = 'users:dashboard'
LOGIN_URL = 'users:login'
LOGOUT_REDIRECT_URL = 'core:home'

# --- Configuración de Email (para Desarrollo) ---
# Imprime los correos en la consola donde se ejecuta 'runserver'.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
