# Generated by Django 5.2.3 on 2025-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
