# Generated by Django 5.2.3 on 2025-07-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, help_text="La noticia será visible a partir de esta fecha si el estado es 'Publicada'.", null=True, verbose_name='Fecha de Publicación'),
        ),
    ]
